sonar.projectKey=joralbornoz_ep2-tienda-perritos
sonar.organization=joralbornoz
sonar.projectName=EP2 Tienda Perritos
sonar.projectVersion=1.0
sonar.sources=backend
sonar.tests=backend/tests
sonar.test.inclusions=backend/tests/**/*.test.js
sonar.exclusions=**/node_modules/**,frontend/**,db/**,backend/tests/**
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info